[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501

[theme]
primaryColor = "#E23744"
backgroundColor = "#0F141C"
secondaryBackgroundColor = "#181C24"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false
